---
output: html_document
---


```{r, echo=FALSE, message=FALSE}
### Exercise 1 ###

library(jsonlite)
library(dplyr)

# Store a variable "movie"

# Write a function that allows you to specify a movie, then does the following:
GetView <-function(movie){
   # Replace all of the spaces in your movie title with plus signs (+)
   movie.no.spaces <- gsub(' ', '+', movie)
   # Construct a search query using YOUR api key
   # The base URL is https://api.nytimes.com/svc/movies/v2/reviews/search.json?
   # See the interactive console for more detail:https://developer.nytimes.com/movie_reviews_v2.json#/Console/GET/reviews/search.json
   
   base.url <-'https://api.nytimes.com/svc/movies/v2/reviews/search.json?'
   api.key <- '&api-key=ecfae53054624483ba1665614fbe9e48'
   request <- paste0(base.url,'query=',movie.no.spaces,api.key,sep="")
   # Request data using your search query
   result <- fromJSON(request)
   # What type of variable does this return? df
   # Flatten the data stored in the `$results` key of the data returned to you
   flattened <- flatten(result$results)
   # From the most recent review, store the headline, short summary, and link to full article each in their own variables
   
   first.review <- flattened[1,] 
   headline <- first.review$headline 
   summary <- first.review$summary_short 
   link <- first.review$link.url 
   # Return an list of the three pieces of information from above
   info <- list(headline=headline, summary=summary, link=link)
   return(info)#remember this
    
}
 
# Test that your function works with a movie of your choice
 
 AlmostFamousInfo <- GetView('Almost Famous')

# Create a variable called `movie.info` by passing your movie to your GetReview function

movie.info <-GetView("Total Recall")
